# Generated by Django 2.0.2 on 2018-02-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180227_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='otherParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='invitee.Invitee'),
        ),
    ]
