# Generated by Django 2.0.2 on 2018-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitee', '0002_invitee_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
