# Generated by Django 2.0.2 on 2018-02-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitee', '0004_auto_20180227_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('fromStatus', models.TextField()),
                ('toStatus', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitee.Invitee')),
            ],
        ),
    ]
