# Generated by Django 2.0.2 on 2018-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
