# Generated by Django 2.0.2 on 2018-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitee', '0003_auto_20180227_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='status',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
